services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ../..:/workspaces:cached

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./data:/opt/keycloak/data
      - ./themes:/opt/keycloak/themes
